#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "uzumibi-on-spin-spike"
version = "0.1.0"
authors = ["Uchio Kondo <udzura@udzura.jp>"]
description = ""

[[trigger.http]]
route = "/..."
component = "uzumibi-on-spin-spike"

[component.uzumibi-on-spin-spike]
source = "../target/wasm32-wasip1/release/uzumibi_on_spin_spike.wasm"
allowed_outbound_hosts = []
[component.uzumibi-on-spin-spike.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
