[package]
name = "uzumibi-gem"
version = "0.1.0-rc1"
edition = "2024"

[dependencies]
mrubyedge = { version = "1.0.15", features = [
    "no-wasi",
], default-features = false }

[dev-dependencies]
mruby-compiler2-sys = "0.2.2"
