[package]
name = "uzumibi-gem"
version = "0.1.0"
edition = "2024"

[dependencies]
#mrubyedge = { version = "1.0.13", features = [
#    "no-wasi",
#], default-features = false }
mrubyedge = { path = "../mrubyedge", features = [
    "no-wasi",
    "mrubyedge-debug",
], default-features = false }

[dev-dependencies]
mruby-compiler2-sys = "0.2.2"
